IDE-579 Add Crtl+N to the Repository Tree Tab to create new attribute
dehilsterlexis/eclide pull request #5
Opened 2016-10-24 14:11 UTC by dehilsterlexis

IDE-579 Add Crtl+N to the Repository Tree Tab to create new attribute

Fixes IDE-579

2016-10-24 21:45 UTC, dehilsterlexis commented
@GordonSmith finally got things straight! Here is the branch you were looking for and it is up to date. Careful: I may just get this git thing... LOL.

2016-10-25 11:24 UTC, GordonSmith commented
Thx - in general no need to do the whole PR thang, the "IDE-579" branch is all I needed.

2017-02-28 11:31 UTC, GordonSmith requested changes

2017-02-28 11:31 UTC, GordonSmith commented on wlib/RepositoryView.h
> +        */
Remove commented code.

2017-02-28 15:49 UTC, dehilsterlexis commented
@richardkchapman @GordonSmith this needs to be closed. It is old and I put it in the wrong place. The new IDE-579 is in the correct branch which I just pushed.

2017-02-28 16:07 UTC, richardkchapman commented
As this is a PR against your own repository, I think only you can close it

2017-02-28 16:44 UTC, dehilsterlexis commented
@richardkchapman you are right. Closed.

2017-02-28 16:44 UTC, closed without merging